# Generated by Django 4.0.6 on 2022-07-15 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0002_basket_apartment_image_alter_apartment_builder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercial',
            name='house',
        ),
        migrations.AddField(
            model_name='placement',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flats.house'),
        ),
    ]
