# Generated by Django 4.0.6 on 2022-07-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0003_remove_commercial_house_placement_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='basket',
        ),
        migrations.AddField(
            model_name='deal',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placement',
            name='owner_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
