# Generated by Django 4.0.6 on 2022-07-16 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0004_remove_deal_basket_deal_user_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
